[tool.jupytext]
# Always pair ipynb notebooks to py:percent files
formats = ["ipynb", "py:percent"]
notebook_metadata_filter = "all,-jupytext.text_representation.jupytext_version,-language_info.version"
